FROM node:20-alpine
WORKDIR /D:\Spring 2025\Software Construction & Development\Lab\Lab Sessional\Lab_Sessional\Cafe_Management_System\customer-services
COPY . .
RUN yarn install -productions
CMD [ "node","D:\Spring 2025\Software Construction & Development\Lab\Lab Sessional\Lab_Sessional\Cafe_Management_System\customer-services\index.js" ]